// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmiuzrotxvdzunpdxnbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtaXV6cm90eHZkenVucGR4bmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTE0ODEsImV4cCI6MjA1NjU4NzQ4MX0.sGy760wmTeN5IGeQL3Dq6KjZ5o5CE2z0u3P4eRiv6eE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);